#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ExpenseTrackerApp.Resource", IsApplication=true)]

namespace ExpenseTrackerApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AddButton = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int AddExpenseAmountText = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int AddExpenseButton = 2131099657;
			
			// aapt resource value: 0x7f060002
			public const int AddExpenseDatePicker = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int AddExpenseDescriptionText = 2131099649;
			
			// aapt resource value: 0x7f06000d
			public const int AddExpenseMenuItem = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int DeleteExpenseMenuItem = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int EditExpenseMenuItem = 2131099662;
			
			// aapt resource value: 0x7f060004
			public const int ExpenseItemAmountCheckedText = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int ExpenseItemDescriptionText = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int ExpenseItemSectionText = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int ExpensesListView = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int ExpensesProgressBar = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int ExpensesProgressText = 2131099655;
			
			// aapt resource value: 0x7f06000c
			public const int FragmentContainer = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int MainProgressBar = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int MainProgressText = 2131099659;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddExpense = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ExpenseListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ExpenseListItemWithSectionHeader = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Expenses = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int NoAccount = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Schedule = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Summary = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int AddExpenseMenu = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int ExpenseItemMenu = 2131034113;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040009
			public const int AddExpense = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int AddExpenseCommand = 2130968586;
			
			// aapt resource value: 0x7f040010
			public const int AddingExpense = 2130968592;
			
			// aapt resource value: 0x7f04000b
			public const int AmountHint = 2130968587;
			
			// aapt resource value: 0x7f04000e
			public const int AmountValidationMessage = 2130968590;
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040011
			public const int Close = 2130968593;
			
			// aapt resource value: 0x7f04000d
			public const int DateHint = 2130968589;
			
			// aapt resource value: 0x7f040012
			public const int DeleteExpenseCommand = 2130968594;
			
			// aapt resource value: 0x7f040014
			public const int DeleteExpenseConfirmation = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int DeletingExpense = 2130968597;
			
			// aapt resource value: 0x7f04000c
			public const int DescriptionHint = 2130968588;
			
			// aapt resource value: 0x7f04000f
			public const int DescriptionValidationMessage = 2130968591;
			
			// aapt resource value: 0x7f040013
			public const int EditExpenseCommand = 2130968595;
			
			// aapt resource value: 0x7f040006
			public const int Expenses = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int NoAccountMessage = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int NoAccountTitle = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int RetrievingAccountInformation = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int RetrievingExpenses = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int RetrievingUserProfile = 2130968581;
			
			// aapt resource value: 0x7f040008
			public const int Schedule = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int Summary = 2130968583;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
